language: node_js
node_js:
 - "16.17.0"

before_install:
 - npm -v

install:
 - npm install -g @angular/cli

script:
 - npm run build
 #- npm test

deploy:
  provider: s3
  access_key_id: process.env.ACCESS_KEY_ID
  secret_access_key: process.env.SECRET_ACCESS_KEY
  bucket: process.env.BUCKET
  skip_cleanup: true
  acl: private # look into this more
  local_dir: ./dist
