language: node_js
node_js:
 - "16.17.0"

branches:
  only:
    - main

before_install:
 - npm -v

install:
 - npm install
 - npm install -g @angular/cli

script:
 - npm run build
 #- npm test

deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: $BUCKET
    skip_cleanup: true
    # acl: private # look into this more
    local_dir: ./dist
    on:
      branch: main
